name: accident_reporter
description: AI-powered car accident reporting app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  image_picker: ^1.2.1
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  google_sign_in: ^7.2.0
  firebase_auth: ^6.4.0
  intl: ^0.20.2
  camera: ^0.12.0+1
  path_provider: ^2.1.5
  path: ^1.9.1
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
